#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header X-Served-By set to the server hostname
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.html
printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
	location / {
		try_files \$uri \$uri/ =404;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
