#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header with the server hostname

apt-get update -y
apt-get install -y nginx

printf 'server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\tadd_header X-Served-By %s;\n\troot /var/www/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\tserver_name _;\n\tlocation / {\n\t\ttry_files $uri $uri/ =404;\n\t}\n}\n' "$HOSTNAME" > /etc/nginx/sites-available/default

service nginx restart
