#!/usr/bin/env bash
# Configures nginx to run and listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-available/default
service nginx restart
