#!/usr/bin/env bash
# Installs and configures Nginx to return "Holberton School for the win!" at root
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
nginx -s stop 2>/dev/null || true
nginx
