#!/usr/bin/env bash
# Installs and configures Nginx to return "Holberton School for the win!" at root
apt-get update -y
apt-get install -y nginx
mkdir -p /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html
cat > /etc/nginx/sites-available/default << 'EOF'
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files $uri $uri/ =404;
        }
}
EOF
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
service nginx restart
