#!/usr/bin/env bash
# Configures Nginx with a 301 redirect on /redirect_me
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" | tee /var/www/html/index.html /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-enabled/default
nginx -t
service nginx restart
