#!/usr/bin/env bash
# Configures Nginx with a 301 redirect on /redirect_me
apt-get update -y
apt-get install -y nginx
mkdir -p /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html
cat > /etc/nginx/sites-available/default << 'EOF'
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
        location / {
                try_files $uri $uri/ =404;
        }
}
EOF
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
service nginx restart
